---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conv-stack-cfg
data:
  conv-stack.yaml: |
    name: conv-stack
    id: cfb5feb0-ce4f-11ec-84fb-b88584a4a6fe
    log-level: 0
    health-port: 6000
    pub-endpoint: tcp://zmq-proxy-service:9200
    sub-endpoint: tcp://zmq-proxy-service:9210
    sub-topics:
      - stack-a-ingress
      - stack-b-ingress
      - net-stack-a-ingress
      - net-stack-b-ingress
    conversions:
      stack-a-ingress: stack-b-egress
      stack-b-ingress: stack-a-egress
      net-stack-a-ingress: net-stack-b-egress
      net-stack-b-ingress: net-stack-a-egress