FROM registry.fedoraproject.org/fedora-minimal:39

ARG TARGETPLATFORM

WORKDIR /zmq-stack

COPY bin/$TARGETPLATFORM/zmq-stack .
ADD config/zmq-stack.yaml ./config/

RUN \
    microdnf install -y zeromq

CMD ./zmq-stack -f ./config/zmq-stack.yaml
