FROM registry.fedoraproject.org/fedora-minimal:39

ARG TARGETPLATFORM

WORKDIR /conv-stack

COPY bin/$TARGETPLATFORM/conv-stack .
ADD config/conv-stack.yaml ./config/

RUN \
    microdnf install -y zeromq

CMD  ./conv-stack -f ./config/conv-stack.yaml
