version: '3.2'

services:

    zmq_sub1:
        image: zmq_sub:latest
        networks:
            - zmq
        command: /zmq_sub -s "tcp://zmq_pub1:9300" -t TOPIC1
  
    zmq_pub1:
        image: zmq_pub:latest
        networks:
            - zmq
        command: /zmq_pub -p 9300 -t TOPIC1

    zmq_sub2:
        image: zmq_sub:latest
        networks:
            - zmq
        command: /zmq_sub -s "tcp://zmq_pub2:9300" -t TOPIC2
  
    zmq_pub2:
        image: zmq_pub:latest
        networks:
            - zmq
        command: /zmq_pub -p 9300 -t TOPIC2

networks:
    zmq:


