FROM fir.love.io:3005/zmq-base:latest

ARG TARGETPLATFORM

WORKDIR /conv-stack

COPY bin/$TARGETPLATFORM/conv-stack .
ADD config/conv-stack.yaml ./config/

CMD  ./conv-stack -f ./config/conv-stack.yaml
