FROM registry.fedoraproject.org/fedora-minimal:39

ARG TARGETPLATFORM

WORKDIR /zmq-proxy

COPY bin/$TARGETPLATFORM/zmq-proxy .
ADD config/zmq-proxy.yaml ./config/

RUN \
    microdnf install -y zeromq

CMD  ./zmq-proxy -f ./config/zmq-proxy.yaml
