
---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zmq-stack-b
      labels:
        app: zmq-stack-b
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: zmq-stack-b
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: zmq-stack-b
            prometheus: "true"
        spec:
          volumes:
            - name: zmq-stack-b-cfg
              configMap:
                name: zmq-stack-b-cfg

          containers:
          - name: zmq-stack-b
            image: fir.love.io:3005/zmq-stack:latest
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: 6000
              initialDelaySeconds: 2
              periodSeconds: 2
            volumeMounts:
              - mountPath: /zmq-stack/config
                name: zmq-stack-b-cfg
                readOnly: true

            ports:
              - name: metrics
                containerPort: 6001
          nodeSelector:
            cputype: amd64


