---
apiVersion: v1
kind: Service
metadata:
  name: zmq-proxy-service
spec:
  type: ClusterIP
  ports:
    - name: xpub
      protocol: TCP
      port: 9200
    - name: xsub
      protocol: TCP
      port: 9210
  selector:
    app: zmq-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zmq-proxy-cfg
data:
  zmq-proxy.yaml: |
    xpub-port: 9200
    xsub-port: 9210
    health-port: 6000
    log-level: 0
    control-endpoint: "inproc://ctrl-endpoint"
    threads: 4
---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zmq-proxy
      labels:
        app: zmq-proxy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: zmq-proxy
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: zmq-proxy
            prometheus: "true"
        spec:
          volumes:
            - name: zmq-proxy-cfg
              configMap:
                name: zmq-proxy-cfg
          containers:
          - name: zmq-proxy
            image: fir.love.io:3005/zmq-proxy:latest
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: 6000
              initialDelaySeconds: 2
              periodSeconds: 2
            volumeMounts:
              - mountPath: /zmq-proxy/config
                name: zmq-proxy-cfg
                readOnly: true

            ports:
            - name: xsub
              containerPort: 9200
            - name: xpub
              containerPort: 9210
            - name: metrics
              containerPort: 6001
          nodeSelector:
            cputype: amd64


