name: ci

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Use container with docker installed
    container: 
      image: catthehacker/ubuntu:act-latest
      volumes:
        # Need to pass /etc/certs through to the custom container
        - /etc/certs:/etc/certs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cd to workspace
        run: cd ${{ gitea.workspace }}

      - name: Build
        uses: https://github.com/addnab/docker-run-action@v3
        with:
          image: fir.love.io:3005/amd64/zmqcross-gcc1321:latest
          options: --rm --pull=always --volumes-from=${{ env.JOB_CONTAINER_NAME }}
          run: |
            g++ --version
            aarch64-linux-gnu-g++ --version
            cmake3 --version
            cd ${{ gitea.workspace }}

            ./build.sh --archlist=x86_64,aarch64 --toolchain=./ArmLinux.cmake

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            debug = true
            [registry."fir.love.io:3005"]
            ca=["/etc/certs/ca.crt"]      

      # Assume base image exists in registry
      # - name: zmq-base
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Containers/Dockerfile.base
      #     push: true
      #     tags: fir.love.io:3005/zmq-base:latest
      #     platforms: linux/amd64,linux/aarch64

      - name: zmq-proxy
        uses: docker/build-push-action@v5
        with:
          context: ./zmq-proxy
          file: ./Containers/Dockerfile.zmq-proxy
          push: true
          tags: fir.love.io:3005/zmq-proxy:latest, fir.love.io:3005/zmq-proxy:${{ github.run_number }}
          platforms: linux/amd64,linux/aarch64

      - name: zmq-stack
        uses: docker/build-push-action@v5
        with:
          context: ./zmq-stack
          file: ./Containers/Dockerfile.zmq-stack
          push: true
          tags: fir.love.io:3005/zmq-stack:latest, fir.love.io:3005/zmq-stack:${{ github.run_number }}
          platforms: linux/amd64,linux/aarch64

      - name: conv-stack
        uses: docker/build-push-action@v5
        with:
          context: ./conv-stack
          file: ./Containers/Dockerfile.conv-stack
          push: true
          tags: fir.love.io:3005/conv-stack:latest, fir.love.io:3005/conv-stack:${{ github.run_number }}
          platforms: linux/amd64,linux/aarch64

      - name: net-stack
        uses: docker/build-push-action@v5
        with:
          context: ./net-stack
          file: ./Containers/Dockerfile.net-stack
          push: true
          tags: fir.love.io:3005/net-stack:latest, fir.love.io:3005/net-stack:${{ github.run_number }}
          platforms: linux/amd64,linux/aarch64

      # - name: apply multiarch deployment
      #   uses: steebchen/kubectl@v2.1.1
      #   with:
      #     config: ${{ secrets.KUBE_CONFIG_DATA }}
      #     command: apply -f multiarch.yaml