---
apiVersion: v1
kind: Service
metadata:
  name: conv-stack
  namespace: {{ $.Release.Namespace }}
  labels:
spec:
  type: ClusterIP
  ports:
    - name: pull
      protocol: TCP
      port: {{ .Values.convPort }}
      targetPort: {{ .Values.convPort }}
  selector:
    app: conv-stack