---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: conv-stack
      namespace: {{ .Release.Namespace }}
      labels:
        app: conv-stack
        app.kubernetes.io/name: conv-stack
    spec:
      replicas: {{ .Values.convStackReplicas }}
      selector:
        matchLabels:
          app: conv-stack
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: conv-stack
            {{ if .Values.prometheus }}prometheus: "true"{{ end }}
        spec:
          volumes:
            - name: conv-stack-cfg
              configMap:
                name: conv-stack-cfg

          containers:
          - name: conv-stack
            image: "{{ .Values.image.registry }}/conv-stack:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            livenessProbe:
              httpGet:
                path: /healthz
                port: {{ .Values.healthzPort }}
              initialDelaySeconds: 2
              periodSeconds: 2
            volumeMounts:
              - mountPath: /conv-stack/config
                name: conv-stack-cfg
                readOnly: true
            ports:
              - name: metrics
                containerPort: {{ .Values.metricsPort }}
              - name: pull
                containerPort: {{ .Values.convPort }}