---
apiVersion: v1
kind: ConfigMap
metadata:
  name: net-stack-cfg
  namespace: {{ .Release.Namespace }}
data:
  net-stack.yaml: |
    name: net-stack
    id: cfb5feb0-ce4f-11ec-84fb-b88584a4a6fe
    log-level: {{ .Values.logLevel }}
    health-port: {{ .Values.healthzPort }}
    pub-endpoints: 
      - tcp://zmq-xpub-proxy-0:{{ .Values.xpubPort }}{{ if lt 1 (.Values.proxyReplicas | int )}}
      - tcp://zmq-xpub-proxy-1:{{ .Values.xpubPort }}{{ if lt 2 (.Values.proxyReplicas | int )}}
      - tcp://zmq-xpub-proxy-2:{{ .Values.xpubPort }}{{ end }}{{ end }}
    sub-endpoint: tcp://zmq-xsub-proxy:{{ .Values.xsubPort }}
    sub-topics:
      - control
    pub-topics:
      - 
    listen-port: 7000