{{- $replicaList := untilStep 0 (int .Values.netStackReplicas ) 1 -}}
  {{- range $index, $replica := $replicaList }}
---
apiVersion: v1
kind: Service
metadata:
  name: net-stack-{{ $index }}-service
  namespace: {{ $.Release.Namespace }}
  labels:
    statefulset.kubernetes.io/pod-name: net-stack-{{ $index }}
spec:
  type: NodePort
  ports:
    - name: ingress
      protocol: TCP
      port: {{ add ($.Values.netStackBasePort | int) $index }}
      targetPort: 7000
      nodePort: {{ add ($.Values.netStackBaseNodePort | int) $index }} 
  selector:
    statefulset.kubernetes.io/pod-name: net-stack-{{ $index }}
  {{- end }}