{{- if .Values.prometheus -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zmq-services
  namespace: {{ .Release.Namespace }}
  labels:
    app: zmq-services
spec:
  selector:
    matchLabels:
      prometheus: "true"
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
{{- end -}}