---
# XSUB service
apiVersion: v1
kind: Service
metadata:
  name: zmq-xsub-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: zmq-proxy
spec:
  ports:
  - port: {{ .Values.xsubPort }}
    name: xsub
    protocol: TCP
  clusterIP: None
  selector:
    app: zmq-proxy
---
# XPUB service-0
apiVersion: v1
kind: Service
metadata:
  name: zmq-xpub-proxy-0
  namespace: {{ .Release.Namespace }}
  labels:
    statefulset.kubernetes.io/pod-name: zmq-proxy-0
spec:
  ports:
  - port: {{ .Values.xpubPort }}
    name: xpub
    protocol: TCP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: zmq-proxy-0
{{ if lt 1 (.Values.proxyReplicas |int) }}
---
# XPUB service-1
apiVersion: v1
kind: Service
metadata:
  name: zmq-xpub-proxy-1
  namespace: {{ .Release.Namespace }}
  labels:
    statefulset.kubernetes.io/pod-name: zmq-proxy-1
spec:
  ports:
  - port: {{ .Values.xpubPort }}
    name: xpub
    protocol: TCP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: zmq-proxy-1
{{ end }}
{{ if lt 2 (.Values.proxyReplicas | int) }}---
# XPUB service-2
apiVersion: v1
kind: Service
metadata:
  name: zmq-xpub-proxy-2
  namespace: {{ .Release.Namespace }}
  labels:
    statefulset.kubernetes.io/pod-name: zmq-proxy-2
spec:
  ports:
  - port: {{ .Values.xpubPort }}
    name: xpub
    protocol: TCP
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: zmq-proxy-2
{{ end }}