---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conv-stack-cfg
  namespace: zmq-test
data:
  conv-stack.yaml: |
    name: conv-stack
    id: cfb5feb0-ce4f-11ec-84fb-b88584a4a6fe
    log-level: 0
    health-port: 6000
    pub-endpoints: 
      - tcp://zmq-xpub-proxy-0:8200
      - tcp://zmq-xpub-proxy-1:8200
      - tcp://zmq-xpub-proxy-2:8200
    sub-endpoint: tcp://zmq-xsub-proxy:8201
    sub-topics:
      - stack-a-ingress
      - stack-b-ingress
      - zmqStack-0-ingress
      - zmqStack-1-ingress
      - zmqStack-2-ingress
      - zmqStack-3-ingress
      - net-stack-a-ingress
      - net-stack-b-ingress
    conversions:
      stack-a-ingress: stack-b-egress
      stack-b-ingress: stack-a-egress
      zmqStack-0-ingress: zmqStack-1-egress
      zmqStack-1-ingress: zmqStack-2-egress
      zmqStack-2-ingress: zmqStack-3-egress
      zmqStack-3-ingress: zmqStack-0-egress
      net-stack-a-ingress: net-stack-b-egress
      net-stack-b-ingress: net-stack-a-egress
---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: conv-stack
      namespace: zmq-test
      labels:
        app: conv-stack
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: conv-stack
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: conv-stack
            prometheus: "true"
        spec:
          volumes:
            - name: conv-stack-cfg
              configMap:
                name: conv-stack-cfg

          containers:
          - name: conv-stack
            image: fir.love.io:3005/conv-stack:latest
            imagePullPolicy: Always
            livenessProbe:
              httpGet:
                path: /healthz
                port: 6000
              initialDelaySeconds: 2
              periodSeconds: 2
            volumeMounts:
              - mountPath: /conv-stack/config
                name: conv-stack-cfg
                readOnly: true

            ports:
              - name: metrics
                containerPort: 6001
          nodeSelector:
            cputype: amd64


