---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zmq-stack-cfg
  namespace: zmq-test
data:
  zmq-stack.yaml: |
    name: zmqStack
    id: cfb5feb0-ce4f-11ec-84fb-b88584a4a6fe
    log-level: 0
    health-port: 6000
    pub-endpoints: 
      - tcp://zmq-xpub-proxy-0:8200
      - tcp://zmq-xpub-proxy-1:8200
      - tcp://zmq-xpub-proxy-2:8200
    sub-endpoint: tcp://zmq-xsub-proxy:8201
    sub-topics:
      - control
    pub-topics:
      - 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zmq-stack
  namespace: zmq-test
spec:
  selector:
    matchLabels:
      app: zmq-stack # has to match .spec.template.metadata.labels
  serviceName: none
  replicas: 2 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: zmq-stack # has to match .spec.selector.matchLabels
        prometheus: "true"

    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: zmq-stack-cfg
          configMap:
            name: zmq-stack-cfg
      containers:
      - name: zmq-proxy
        image: fir.love.io:3005/zmq-stack:latest
        ports:
        - name: metrics
          containerPort: 6001
        volumeMounts:
        - mountPath: /zmq-stack/config
          name: zmq-stack-cfg
          readOnly: true
      nodeSelector:
        cputype: amd64